"use client";
import Aside from "@/components/Aside";
import "./globals.css";
import { Inter } from "next/font/google";
import { SupabaseProvider } from "@/context/SupabaseContext/SupabaseProvider";
import { AuthFormProvider } from "@/context/AuthFormContext/AuthFormProvider";
import AppProvider from "@/context/AppContext/AppProvider";
import Loading from "./loading";
import { Suspense } from "react";
// import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="">
            <body className={`${inter.className} bg-[#14161e] scrollbar  text-[#cedadb] `}>
                <SupabaseProvider>
                    <AuthFormProvider>
                        <AppProvider>
                            <Suspense fallback={<Loading />}>
                                <div className="flex h-screen w-full overflow-hidden">
                                    <Aside />
                                    {children}
                                </div>
                            </Suspense>
                        </AppProvider>
                    </AuthFormProvider>
                </SupabaseProvider>
            </body>
        </html>
    );
}

// const telegraf = localFont({
//   src: [
//     {
//       path: "./telegraf-regular.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "./telegraf-medium.woff2",
//       weight: "500",
//       style: "italic",
//     },
//     {
//       path: "./telegraf-semibold.woff2",
//       weight: "600",
//       style: "normal",
//     },
//     {
//       path: "./telegraf-bold.woff2",
//       weight: "700",
//       style: "italic",
//     },
//   ],
// });
